### ISSUE TITLE
Unable to switch directory when create publish profile | 1.4.0-nightly.229372.feac99a 

### ISSUE THREAD

**Issue by junczhu** [microsoft/BotFramework-Composer-Nightlies#2]
## Describe the bug

Users are not able to select directory when create publish profile.
The default directory has no subscription.

## Version

1.4.0-nightly.229372.feac99a

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

create publish profile

## Expected behavior

User should be able to select Directory

## Screenshots

![image](https://user-images.githubusercontent.com/74894646/114144149-98c97780-9947-11eb-9b5e-d9dd1b8777bf.png)
![image](https://user-images.githubusercontent.com/74894646/114144215-aaab1a80-9947-11eb-9888-780bc605c099.png)

## Additional context

[localhost-1617267769368.log](https://github.com/microsoft/BotFramework-Composer-Nightlies/files/6283928/localhost-1617267769368.log)
[consolelogs.log](https://github.com/microsoft/BotFramework-Composer-Nightlies/files/6283932/consolelogs.log)

**Comment by sinnypan** [comment]
Hello, I also encountered the same issue using latest nightbird version, after reboot my laptop or restart the bot composer, still no luck. I'm using Bot composer V2.1.1 with nightbird version
![image](https://user-images.githubusercontent.com/41359405/146486113-fc71af83-88a2-49cd-8d44-19c1b83b97f8.png)

**Comment by junczhu** [comment]
marked `Closed` for no longer tracking
